swagger: "2.0"
info:
  version: 1.0.0
  title: Blog Api
host: codercat.ru
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /posts:
    get:
      operationId: getPosts
      parameters:
        - name: numb
          in: query
          required: false
          type: integer
        - name: limit
          in: query
          required: false
          type: integer
      responses:
        200:
          description: list posts
          schema:
            type: array
            items:
              $ref: '#/definitions/Post'
definitions:
  Post:
    type: "object"
    required:
      - title
      - body
      - id
    properties:
      title:
        type: string
      body:
        type: string
      id:
        type: string