swagger: "2.0"
info:
  version: 1.0.0
  title: Blog Api
host: codercat.ru
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /posts:
    get:
      operationId: getPosts
      parameters:
        - name: page
          in: query
          required: false
          type: integer
        - name: page_size
          in: query
          required: false
          type: integer
        - name: limit
          in: query
          required: false
          type: integer
      responses:
        200:
          description: list posts
          schema:
            type: array
            items:
              $ref: '#/definitions/Post'
  /post/{id}:
    get:
      operationId: getPost
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: post
          schema:
            $ref: '#/definitions/Post'
        404:
          description: not found
  /post:
    post:
      operationId: createPost
      security:
        - basicAuth: []
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: '#/definitions/Post'
      responses:
        200:
          description: post created
        409:
          description: post with this id already exists

definitions:
  Post:
    type: "object"
    required:
      - title
      - body
      - id
    properties:
      title:
        type: string
      body:
        type: string
      id:
        type: string

securityDefinitions:
  basicAuth:
    type: basic