
name: remote ssh command

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd /root/CoderBlog; git pull; cp -r web/. /var/www/html/;
