name: Scala CI

on:
  push:
    paths: 
    - 'backend/**'
    - '.github/workflows/scala.yml'
    branches:
    - dev
  pull_request:
    branches: 
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run build
      working-directory: backend
      run: sbt assembly
    - name: Copy jar
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "backend/target/scala-2.13/CoderBlog.jar"
        target: "/root/"
        strip_components: 3
    - name: Restart app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: systemctl restart CoderBlog.service
